export const GET_FORECAST = "GET_FORECAST";
export const FORECAST_FETCH_SUCCESS = "FORECAST_FETCH_SUCCESS";
export const FORECAST_FETCH_FAIL = "FORECAST_FETCH_FAIL";
export const SAVE_CITY_FORECAST = "SAVE_CITY_FORECAST";
export const DELETE_CITY_FORECAST = "DELETE_CITY_FORECAST";



